### ISSUE TITLE
volume deform implementation

### ISSUE THREAD

**Issue by eshafeeqe** [niessner/Opt#86]
Hello, 

I am assuming that the paper : https://arxiv.org/abs/1603.08161 used this optimization package. And a small version of this deformation model is given in the example: volumetric_mesh_deformation. Since the example shown with small grid and its working really good. So I modified the same code with manual constraints for a TSDF grid size of 128x128x128. So in my experiment, I got 12 sec for an iteration of the optimization.  And the paper here is showing the same optimization for bigger grid size (may be 512x512x512) with in real time. Is there any way to improve the optimization time by using Opt. Or any fine tuning parameters to be adjusted? Any kind of lead will be appreciated. 

Thanks and Regards
Shafeeq E

**Comment by niessner** [comment]
It should work. First of all, in volume deform the deformation grid is typically lower resolution than the actual TSDF grid size (one or two levels below 512^3). You also need a hierarchy even on top of that for faster convergence. Last, you need to "exclude" (there is a feature in opt -> see PoissonImageEditing example) in order to remove blocks from the optimization where no data lives.

Hope that helps :)
